export const HomeStyles = {
  astronaut: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  createSongContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '40vh',
    marginTop: '10vh',
  },
  createSongTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginTop: '3vh',
  },
  createSongInputContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '3vh',
  },
  createSongInput: {
    width: '30vw',
    minWidth: '200px',
    borderTopRightRadius: '0px',
    borderBottomRightRadius: '0px',
  },
  createSongInputButton: {
    borderColor: '#676BB9',
    backgroundColor: '#676BB9',
    color: '#FFFFFF',
    height: '48px',
    borderTopRightRadius: '5px',
    borderBottomRightRadius: '5px',
    borderTopLeftRadius: '0px',
    borderBottomLeftRadius: '0px',
    fontWeight: '500',
  },
  audioPlayerContainer: {
    marginTop: '40px',
    padding: '1px',
    height: '56px',
    width: '345px',
    backgroundColor: '#676BB9',
    borderRadius: '50px',
    justifyContent: 'center',
    alignItems: 'center',
  },
}
